# E-Commerce Sales Analysis — Pandas Database Project

**Project:** Read, analyse, and write back e-commerce sales data using PostgreSQL and Pandas.

**Functions covered:**
| Function | Used in |
|---|---|
| `pd.read_sql()` | Section 3 — general reads |
| `pd.read_sql_table()` | Section 3 — full table load |
| `pd.read_sql_query()` | Section 4 — filtered & joined queries |
| `df.to_sql()` | Section 6 — write results back |
| `pd.io.sql.get_schema()` | Section 5 — inspect schema before writing |
| `chunksize` | Section 4 — large table streaming |
| `dtype` | Section 3 — type control |
| `parse_dates` | Section 3 — auto date parsing |
| `index_col` | Section 3 — set DF index |
| `params` | Section 4 — safe parameterized queries |

---
**Database:** PostgreSQL · **Schema:** `ecommerce`

## Section 1 — Database Setup

We use SQLAlchemy to create a connection engine. All Pandas read/write functions accept this engine via the `con=` parameter.

> **Note:** Replace the connection string with your own PostgreSQL credentials before running.

In [18]:
import pandas as pd
import numpy as np
from sqlalchemy import create_engine, text
from pandas.io import sql as pd_sql
import warnings
warnings.filterwarnings('ignore')

# --- Connection string format:
# postgresql://username:password@host:port/database_name
DB_URL = "postgresql://postgres:1234@localhost:5432/ecommerce_db"

engine = create_engine(DB_URL, pool_pre_ping=True)

# Test connection
with engine.connect() as conn:
    result = conn.execute(text("SELECT version()"))
    print("Connected to:", result.fetchone()[0])

Connected to: PostgreSQL 18.3 on x86_64-windows, compiled by msvc-19.44.35223, 64-bit

## Section 2 — Create Sample Tables

Run this section once to populate your database with realistic e-commerce data.
Skip it if your tables already exist.

In [19]:
# ── Sample data ──────────────────────────────────────────────

customers = pd.DataFrame({
    'customer_id': range(1, 11),
    'name':        ['Alice Chen','Bob Malik','Carla Ruiz','David Kim','Eva Patel',
                    'Faisal Ahmed','Grace Liu','Hamid Raza','Ines Costa','Javed Iqbal'],
    'city':        ['Lahore','Karachi','Islamabad','Lahore','Karachi',
                    'Islamabad','Lahore','Karachi','Islamabad','Lahore'],
    'segment':     ['Premium','Standard','Premium','Standard','Premium',
                    'Standard','Premium','Standard','Premium','Standard'],
    'joined_at':   pd.date_range('2022-01-01', periods=10, freq='45D')
})

products = pd.DataFrame({
    'product_id':  range(1, 8),
    'name':        ['Laptop','Headphones','Mouse','Keyboard','Monitor','Webcam','Desk Lamp'],
    'category':    ['Electronics','Electronics','Accessories','Accessories',
                    'Electronics','Accessories','Home Office'],
    'price':       [85000.0, 4500.0, 1200.0, 2500.0, 32000.0, 6000.0, 1800.0],
    'stock':       [50, 200, 500, 300, 40, 150, 250]
})

np.random.seed(42)
n = 200
orders = pd.DataFrame({
    'order_id':     range(1001, 1001 + n),
    'customer_id':  np.random.randint(1, 11, n),
    'product_id':   np.random.randint(1, 8, n),
    'quantity':     np.random.randint(1, 6, n),
    'discount_pct': np.random.choice([0, 5, 10, 15], n),
    'status':       np.random.choice(['completed','pending','cancelled'], n,
                                      p=[0.75, 0.15, 0.10]),
    'ordered_at':   pd.date_range('2024-01-01', periods=n, freq='40h')
})

# Write all three tables to PostgreSQL
for df, table in [(customers,'customers'),(products,'products'),(orders,'orders')]:
    df.to_sql(table, con=engine, if_exists='replace', index=False)
    print(f"  Wrote {len(df)} rows → {table}")

print("\nSample data loaded successfully.")

  Wrote 10 rows → customers
  Wrote 7 rows → products
  Wrote 200 rows → orders

Sample data loaded successfully.

## Section 3 — Reading Data with pd.read_sql()

`pd.read_sql()` is the universal reader. It auto-detects whether you pass a table name or a SQL query string.

Here we also demonstrate `index_col`, `parse_dates`, and `dtype`.

In [20]:
# ── 3a. pd.read_sql() with a table name ──────────────────────
# Reads the entire 'products' table. Equivalent to SELECT * FROM products.

products_df = pd.read_sql(
    "products",
    con=engine,
    index_col="product_id"   # use DB primary key as DataFrame index
)

print("Shape:", products_df.shape)
print("Index name:", products_df.index.name)
products_df

Shape: (7, 4)
Index name: product_id

                  name     category    price  stock
product_id
1               Laptop  Electronics  85000.0     50
2           Headphones  Electronics   4500.0    200
3                Mouse  Accessories   1200.0    500
4             Keyboard  Accessories   2500.0    300
5              Monitor  Electronics  32000.0     40
6               Webcam  Accessories   6000.0    150
7            Desk Lamp  Home Office   1800.0    250

In [21]:
# ── 3b. pd.read_sql_table() — explicit full-table read ───────
# Same result as 3a but more explicit. Requires SQLAlchemy engine.

customers_df = pd.read_sql_table(
    "customers",
    con=engine,
    index_col="customer_id",
    parse_dates=["joined_at"]   # auto-convert to datetime64
)

print("Dtypes:")
print(customers_df.dtypes)
print()
customers_df.head()

Dtypes:
name                    str
city                    str
segment                 str
joined_at    datetime64[us]
dtype: object

                   name       city   segment  joined_at
customer_id
1            Alice Chen     Lahore   Premium 2022-01-01
2             Bob Malik    Karachi  Standard 2022-02-15
3            Carla Ruiz  Islamabad   Premium 2022-04-01
4             David Kim     Lahore  Standard 2022-05-16
5             Eva Patel    Karachi   Premium 2022-06-30

In [22]:
# ── 3c. pd.read_sql() with dtype overrides ───────────────────
# discount_pct and quantity stored as int64 by default.
# We force them to float32 to save memory and match downstream calculations.

orders_df = pd.read_sql(
    "orders",
    con=engine,
    parse_dates=["ordered_at"],
    dtype={
        "quantity":     "float32",
        "discount_pct": "float32",
        "status":       "category"   # efficient for low-cardinality strings
    }
)

print("Dtypes after override:")
print(orders_df[['quantity','discount_pct','status']].dtypes)
print(f"\nMemory usage: {orders_df.memory_usage(deep=True).sum() / 1024:.1f} KB")
orders_df.head()

Dtypes after override:
quantity        int64
discount_pct    int64
status            str
dtype: object

Memory usage: 22.3 KB

,order_id,customer_id,product_id,quantity,discount_pct,status,ordered_at
0,1001,7,6,3,5,completed,2024-01-01 00:00:00
1,1002,4,3,1,10,completed,2024-01-02 16:00:00
2,1003,8,7,2,5,pending,2024-01-04 08:00:00
3,1004,5,1,5,0,completed,2024-01-06 00:00:00
4,1005,7,1,2,15,completed,2024-01-07 16:00:00

## Section 4 — Filtered & Joined Queries with pd.read_sql_query()

`pd.read_sql_query()` runs any SQL you write — filters, JOINs, GROUP BY, CTEs.
We also demonstrate `params=` for safe parameterized queries and `chunksize` for large tables.

In [23]:
# ── 4a. Parameterized query with params= ─────────────────────
# ALWAYS use params= when user input or external values enter your SQL.
# Never use f-strings — they create SQL injection vulnerabilities.

target_city   = "Lahore"      # imagine this came from user input
min_order_qty = 2

query = """
    SELECT o.order_id, c.name AS customer, c.city,
           p.name AS product, p.category,
           o.quantity, o.discount_pct, o.status, o.ordered_at
    FROM orders o
    JOIN customers c ON o.customer_id = c.customer_id
    JOIN products  p ON o.product_id  = p.product_id
    WHERE c.city = %s
      AND o.quantity >= %s
      AND o.status = 'completed'
    ORDER BY o.ordered_at DESC
"""

lahore_orders = pd.read_sql_query(
    query,
    con=engine,
    parse_dates=["ordered_at"],
    params=(target_city, min_order_qty)   # bound safely by the DB driver
)

print(f"Completed orders from {target_city} with qty >= {min_order_qty}: {len(lahore_orders)}")
lahore_orders.head(8)

Completed orders from Lahore with qty >= 2: 48

,order_id,customer,city,product,category,quantity,discount_pct,status,ordered_at
0,1198,David Kim,Lahore,Desk Lamp,Home Office,4,5,completed,2024-11-24 08:00:00
1,1192,Grace Liu,Lahore,Mouse,Accessories,3,5,completed,2024-11-14 08:00:00
2,1191,David Kim,Lahore,Keyboard,Accessories,3,10,completed,2024-11-12 16:00:00
3,1188,Javed Iqbal,Lahore,Laptop,Electronics,5,0,completed,2024-11-07 16:00:00
4,1184,Alice Chen,Lahore,Laptop,Electronics,5,5,completed,2024-11-01 00:00:00
5,1177,Alice Chen,Lahore,Mouse,Accessories,4,0,completed,2024-10-20 08:00:00
6,1174,Alice Chen,Lahore,Headphones,Electronics,3,0,completed,2024-10-15 08:00:00
7,1172,Alice Chen,Lahore,Desk Lamp,Home Office,5,0,completed,2024-10-12 00:00:00

In [24]:
# ── 4b. Aggregation query — revenue by category ──────────────
# JOIN orders → products, compute revenue per category.

revenue_query = """
    SELECT
        p.category,
        COUNT(o.order_id)                                          AS total_orders,
        SUM(o.quantity)                                            AS units_sold,
        SUM(o.quantity * p.price * (1 - o.discount_pct / 100.0))  AS net_revenue
    FROM orders o
    JOIN products p ON o.product_id = p.product_id
    WHERE o.status = 'completed'
    GROUP BY p.category
    ORDER BY net_revenue DESC
"""

revenue_by_category = pd.read_sql_query(
    revenue_query,
    con=engine,
    dtype={"net_revenue": "float64"}
)

revenue_by_category["net_revenue"] = revenue_by_category["net_revenue"].round(2)
revenue_by_category

      category  total_orders  units_sold  net_revenue
0  Electronics            63         205    9978500.0
1  Accessories            68         191     608535.0
2  Home Office            19          62     104130.0

In [25]:
# ── 4c. chunksize — streaming a large result set ─────────────
# If orders had millions of rows, loading all at once would crash.
# chunksize= returns a generator; we process each chunk and collect results.

chunks = pd.read_sql(
    "SELECT order_id, quantity, discount_pct FROM orders WHERE status = 'completed'",
    con=engine,
    chunksize=50   # process 50 rows at a time (use 10_000+ in production)
)

# Compute average discount per chunk, then combine
chunk_stats = []
for i, chunk in enumerate(chunks):
    chunk_stats.append({
        "chunk":        i + 1,
        "rows":         len(chunk),
        "avg_discount": round(chunk["discount_pct"].mean(), 2),
        "total_units":  int(chunk["quantity"].sum())
    })

chunks_df = pd.DataFrame(chunk_stats)
print(f"Processed {len(chunks_df)} chunks")
print(f"Overall avg discount: {chunks_df['avg_discount'].mean():.2f}%")
chunks_df

Processed 3 chunks
Overall avg discount: 7.07%

   chunk  rows  avg_discount  total_units
0      1    50           7.1          159
1      2    50           7.7          146
2      3    50           6.4          153

## Section 5 — Inspect Schema with pd.io.sql.get_schema()

Before writing a new DataFrame to the database, use `get_schema()` to preview the
`CREATE TABLE` statement Pandas would generate. No data is written — it's purely for inspection.

In [26]:
# ── 5a. Build the analysis DataFrame we plan to write ────────

# Monthly revenue summary — what we'll write back to the DB
orders_full = pd.read_sql(
    "SELECT o.*, p.price FROM orders o JOIN products p ON o.product_id = p.product_id",
    con=engine,
    parse_dates=["ordered_at"]
)

orders_full["revenue"] = (
    orders_full["quantity"] *
    orders_full["price"] *
    (1 - orders_full["discount_pct"] / 100)
)

monthly_summary = (
    orders_full[orders_full["status"] == "completed"]
    .groupby(orders_full["ordered_at"].dt.to_period("M"))
    .agg(
        total_orders=("order_id",  "count"),
        total_units =("quantity",  "sum"),
        gross_revenue=("revenue",  "sum"),
        avg_discount=("discount_pct", "mean")
    )
    .reset_index()
)
monthly_summary["ordered_at"] = monthly_summary["ordered_at"].astype(str)
monthly_summary = monthly_summary.rename(columns={"ordered_at": "month"})
monthly_summary["gross_revenue"] = monthly_summary["gross_revenue"].round(2)
monthly_summary["avg_discount"]  = monthly_summary["avg_discount"].round(2)

print("Preview of data to be written:")
monthly_summary.head()

Preview of data to be written:

     month  total_orders  total_units  gross_revenue  avg_discount
0  2024-01            14           44       728640.0          5.71
1  2024-02            11           36      1196745.0          6.36
2  2024-03            15           45      1128890.0          9.33
3  2024-04            15           49      1638235.0          5.33
4  2024-05            14           41       924945.0          5.71

In [27]:
# ── 5b. Inspect schema BEFORE writing ────────────────────────
# get_schema() shows exactly what CREATE TABLE Pandas would run.
# Use this to catch type mismatches before committing to the DB.

schema_sql = pd_sql.get_schema(monthly_summary, "monthly_revenue_summary", con=engine)
print(schema_sql)

CREATE TABLE monthly_revenue_summary (
	month TEXT,
	total_orders BIGINT,
	total_units BIGINT,
	gross_revenue FLOAT(53),
	avg_discount FLOAT(53)
)

## Section 6 — Writing Results Back with df.to_sql()

After analysis, write the summary tables back to PostgreSQL so other tools
(dashboards, reports, other scripts) can query them directly.

In [28]:
# ── 6a. Write monthly revenue summary ────────────────────────

monthly_summary.to_sql(
    "monthly_revenue_summary",
    con=engine,
    if_exists="replace",   # drop & recreate if already exists
    index=False,           # don't write the DataFrame index as a column
    method="multi"         # faster multi-row INSERT (vs one INSERT per row)
)

print(f"Written {len(monthly_summary)} rows → monthly_revenue_summary")

# Verify by reading it back
verify = pd.read_sql("monthly_revenue_summary", con=engine)
print("Read back:", verify.shape)
verify

Written 11 rows → monthly_revenue_summary
Read back: (11, 5)

      month  total_orders  total_units  gross_revenue  avg_discount
0   2024-01            14           44       728640.0          5.71
1   2024-02            11           36      1196745.0          6.36
2   2024-03            15           45      1128890.0          9.33
3   2024-04            15           49      1638235.0          5.33
4   2024-05            14           41       924945.0          5.71
5   2024-06            15           46       188625.0          7.67
6   2024-07            17           49      1484650.0         11.18
7   2024-08            12           39       863500.0          7.08
8   2024-09            13           29       181730.0          7.69
9   2024-10            15           49      1454825.0          5.67
10  2024-11             9           31       900380.0          3.89

In [29]:
# ── 6b. Write customer-level summary ─────────────────────────

customer_summary = (
    orders_full[orders_full["status"] == "completed"]
    .groupby("customer_id")
    .agg(
        total_orders  =("order_id",  "count"),
        total_spent   =("revenue",   "sum"),
        avg_order_val =("revenue",   "mean"),
        last_order    =("ordered_at","max")
    )
    .reset_index()
)
customer_summary["total_spent"]    = customer_summary["total_spent"].round(2)
customer_summary["avg_order_val"]  = customer_summary["avg_order_val"].round(2)

# Tag VIP customers (top 30% by spend)
threshold = customer_summary["total_spent"].quantile(0.70)
customer_summary["is_vip"] = customer_summary["total_spent"] >= threshold

customer_summary.to_sql(
    "customer_summary",
    con=engine,
    if_exists="replace",
    index=False,
    method="multi"
)

print(f"Written {len(customer_summary)} rows → customer_summary")
print(f"VIP customers: {customer_summary['is_vip'].sum()}")
customer_summary

Written 10 rows → customer_summary
VIP customers: 3

,customer_id,total_orders,total_spent,avg_order_val,last_order,is_vip
0,1,12,883855.0,73654.58,2024-11-01 00:00:00,False
1,2,12,1208385.0,100698.75,2024-11-26 00:00:00,True
2,3,16,719940.0,44996.25,2024-11-02 16:00:00,False
3,4,16,1102945.0,68934.06,2024-11-24 08:00:00,False
4,5,15,954825.0,63655.00,2024-10-28 16:00:00,False
5,6,10,758560.0,75856.00,2024-11-27 16:00:00,False
6,7,21,920435.0,43830.24,2024-11-14 08:00:00,False
7,8,19,769275.0,40488.16,2024-10-17 00:00:00,False
8,9,13,1204595.0,92661.15,2024-09-05 08:00:00,True
9,10,16,2168350.0,135521.88,2024-11-07 16:00:00,True

In [30]:
# ── 6c. to_sql with if_exists='append' ───────────────────────
# Useful for incremental loads — add new rows without replacing old ones.

new_product = pd.DataFrame([{
    'product_id': 8,
    'name':       'USB Hub',
    'category':   'Accessories',
    'price':      2200.0,
    'stock':      180
}])

new_product.to_sql(
    "products",
    con=engine,
    if_exists="append",  # add to existing table — don't drop it
    index=False
)

# Confirm total rows
count = pd.read_sql("SELECT COUNT(*) AS n FROM products", con=engine)
print("Total products now:", count['n'].iloc[0])

Total products now: 8

## Section 7 — Final Summary

Read the two result tables we created and print a final report.

In [31]:
# ── Final report ─────────────────────────────────────────────

rev   = pd.read_sql("monthly_revenue_summary", con=engine)
cust  = pd.read_sql("customer_summary",         con=engine)

print("=" * 50)
print("       E-COMMERCE ANALYSIS REPORT")
print("=" * 50)
print(f"  Total months analysed : {len(rev)}")
print(f"  Total completed orders: {rev['total_orders'].sum()}")
print(f"  Total gross revenue   : PKR {rev['gross_revenue'].sum():,.0f}")
print(f"  Best month            : {rev.loc[rev['gross_revenue'].idxmax(), 'month']}")
print(f"  Avg monthly revenue   : PKR {rev['gross_revenue'].mean():,.0f}")
print()
print(f"  Total customers       : {len(cust)}")
print(f"  VIP customers (top 30%): {cust['is_vip'].sum()}")
print(f"  Highest spender       : PKR {cust['total_spent'].max():,.0f}")
print("=" * 50)

print("\nMonthly revenue trend:")
rev[["month","total_orders","gross_revenue"]].to_string(index=False)

==================================================
       E-COMMERCE ANALYSIS REPORT
==================================================
  Total months analysed : 11
  Total completed orders: 150
  Total gross revenue   : PKR 10,691,165
  Best month            : 2024-04
  Avg monthly revenue   : PKR 971,924

  Total customers       : 10
  VIP customers (top 30%): 3
  Highest spender       : PKR 2,168,350
==================================================

Monthly revenue trend:

'  month  total_orders  gross_revenue\n2024-01            14       728640.0\n2024-02            11      1196745.0\n2024-03            15      1128890.0\n2024-04            15      1638235.0\n2024-05            14       924945.0\n2024-06            15       188625.0\n2024-07            17      1484650.0\n2024-08            12       863500.0\n2024-09            13       181730.0\n2024-10            15      1454825.0\n2024-11             9       900380.0'

In [32]:
# ── Cleanup — close engine ────────────────────────────────────
engine.dispose()
print("Connection pool closed.")

Connection pool closed.